name: Latest blog post workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs exactly at midnight (00:00) every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with Medium posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@himath.nimpura"
          max_post_count: 5
          # This template creates a clickable image and title for each post
          template: '<table><tr><td><a href="$url"><img src="$path" width="150px" height="auto" /></a></td><td><a href="$url">$title</a><br/>$date</td></tr></table>'
